### ISSUE TITLE
Flask implementation

### ISSUE THREAD

**Issue by ApolllonDev** [ApolllonDev/Python-Projects#22]
# Bank Application should have following routes

- [x] landing
- [x] login
- [x] register
- [x] forgot password
- [x] about
- [x] contact
- [x] account
- [x] transaction
- [x] user
- [x] search

**Comment by Traybot360** [comment]
[example of login form](https://github.com/ApolllonDev/Python-Projects/blob/master/Bank/flask/templates/login.html)
